-- create table city
-- (
--     "id" serial primary key,
--     "name" varchar(256) not null
-- );
--
-- create table city_prices
-- (
--     "id"          serial primary key,
--
--     "last_update" timestamp not null
-- );